### ISSUE TITLE
Torrents not scraping. 

### ISSUE THREAD

**Issue by Tinuz97** [Mr-Kodi/repository.fenomscrapers#26]
Hi @Tikipeter @123Venom, I'm on my mobile right now (not able to post a complete log for now, because on the phone it is difficult on a little screen), but I found this part in the log :+1:

2021-12-10 11:52:45.217 T:10128   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/sources_fenomscrapers/torrents/limetorrents.py", line 81, in get_sources

Started since 2.0.6 update (I see allot of people with the same issue).

I hope this little part of the log is OK, otherwise I can post the full log in the evening. (early morning here).

**Comment by Tinuz97** [comment]
Nevermind, found the debug option.
But can't copy the link, so I post the log from Fenomscrapers log file here :+1:


[2021-12-10 12:04:50] [COLOR red][ FENOMSCRAPERS ERROR ][/COLOR]: RLSBB - Exception: 
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/sources_fenomscrapers/hosters/rlsbb.py", line 30, in sources
    scraper = cfscrape.create_scraper()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 320, in create_scraper
    scraper = cls(**kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 145, in __init__
    self.user_agent = User_Agent(
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/user_agent/__init__.py", line 20, in __init__
    self.loadUserAgent(*args, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/user_agent/__init__.py", line 74, in loadUserAgent
    with open(os.path.join(os.path.dirname(__file__), 'browsers.json'), 'r') as fp:
KeyError: '_bootlocale'
 (NORMALIZED by log_utils.log())
[2021-12-10 12:04:50] [COLOR red][ FENOMSCRAPERS ERROR ][/COLOR]: TORRENTAPI - Exception: 
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/sources_fenomscrapers/torrents/torrentapi.py", line 43, in sources
    self.scraper = cfscrape.create_scraper()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 320, in create_scraper
    scraper = cls(**kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 145, in __init__
    self.user_agent = User_Agent(
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/user_agent/__init__.py", line 20, in __init__
    self.loadUserAgent(*args, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/user_agent/__init__.py", line 74, in loadUserAgent
    with open(os.path.join(os.path.dirname(__file__), 'browsers.json'), 'r') as fp:
KeyError: '_bootlocale'
 (NORMALIZED by log_utils.log())
[2021-12-10 12:04:50] [COLOR red][ FENOMSCRAPERS ERROR ][/COLOR]: TORRENTGALAXY - Exception: 
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/sources_fenomscrapers/torrents/torrentgalaxy.py", line 30, in sources
    scraper = cfscrape.create_scraper()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 320, in create_scraper
    scraper = cls(**kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 145, in __init__
    self.user_agent = User_Agent(
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/user_agent/__init__.py", line 20, in __init__
    self.loadUserAgent(*args, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/user_agent/__init__.py", line 74, in loadUserAgent
    with open(os.path.join(os.path.dirname(__file__), 'browsers.json'), 'r') as fp:
KeyError: '_bootlocale'
 (NORMALIZED by log_utils.log())
[2021-12-10 12:04:51] [COLOR red][ FENOMSCRAPERS ERROR ][/COLOR]: MAXRLS - Exception: 
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/sources_fenomscrapers/hosters/maxrls.py", line 31, in sources
    scraper = cfscrape.create_scraper()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 320, in create_scraper
    scraper = cls(**kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 145, in __init__
    self.user_agent = User_Agent(
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/user_agent/__init__.py", line 20, in __init__
    self.loadUserAgent(*args, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/user_agent/__init__.py", line 74, in loadUserAgent
    with open(os.path.join(os.path.dirname(__file__), 'browsers.json'), 'r') as fp:
KeyError: '_bootlocale'
 (NORMALIZED by log_utils.log())
[2021-12-10 12:04:51] [COLOR red][ FENOMSCRAPERS ERROR ][/COLOR]: SCENERLS - Exception: 
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/sources_fenomscrapers/hosters/scenerls.py", line 30, in sources
    scraper = cfscrape.create_scraper()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 320, in create_scraper
    scraper = cls(**kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 145, in __init__
    self.user_agent = User_Agent(
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/user_agent/__init__.py", line 20, in __init__
    self.loadUserAgent(*args, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/user_agent/__init__.py", line 74, in loadUserAgent
    with open(os.path.join(os.path.dirname(__file__), 'browsers.json'), 'r') as fp:
KeyError: '_bootlocale'
 (NORMALIZED by log_utils.log())
[2021-12-10 12:05:01] [COLOR red][ FENOMSCRAPERS ERROR ][/COLOR]: From func name: /lib/fenomscrapers/modules/client.py.request() Line # :110
                       msg : Request-Error url=(https://bt4g.org/movie/search/Finch+2021/byseeders/1) -> URLError -> <urlopen error [Errno 99] Cannot assign requested address>
[2021-12-10 12:05:01] [COLOR red][ FENOMSCRAPERS ERROR ][/COLOR]: LIMETORRENTS - Exception: 
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x733e899700>: Failed to establish a new connection: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.limetorrents.pro', port=443): Max retries exceeded with url: /search/movies/Finch-2021/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x733e899700>: Failed to establish a new connection: [Errno 99] Cannot assign requested address'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/sources_fenomscrapers/torrents/limetorrents.py", line 67, in get_sources
    r = self.scraper.get(link, headers=headers, timeout=10).text
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 260, in request
    self.perform_request(method, url, *args, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.fenomscrapers/lib/fenomscrapers/modules/cfscrape/__init__.py", line 193, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.limetorrents.pro', port=443): Max retries exceeded with url: /search/movies/Finch-2021/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x733e899700>: Failed to establish a new connection: [Errno 99] Cannot assign requested address'))
 (NORMALIZED by log_utils.log())
[2021-12-10 12:05:05] [COLOR red][ FENOMSCRAPERS ERROR ][/COLOR]: From func name: /lib/fenomscrapers/modules/client.py.request() Line # :110
                       msg : Request-Error url=(http://get.myvideolinks.net/?s=Finch+2021) -> URLError -> <urlopen error timed out>
[2021-12-10 12:05:24] [COLOR red][ FENOMSCRAPERS INFO ][/COLOR]: FenomScrapers log file uploaded to: https://paste.kodi.tv/baximenaki

**Comment by unknown2this** [comment]
Seems like the issue is related to the Undesirables group because disabling Undesirables under the Torrent category allows foro scraping to work again.

**Comment by james-nduka** [comment]
Plans for a fix? (I know there’s a workaround but not everyone would)

**Comment by 123Venom** [comment]
I've replied to the thought that the undesirables is the cause here....
https://github.com/123Venom/plugin.video.venom/issues/151#issuecomment-991200761

@Tinuz97 as for your log errors.  I don't think those are the cause of the issue either.  A good many of those log errors are coming from the cfscrape/cloudflare module and unfortunately that's written by Venomous and I'd have to get in touch with him on the user agent assignment failure because it's not my code.  You have some connection issues going on there also that I'm not sure if they're blocked for you or not.

**Comment by Tinuz97** [comment]
> I've replied to the thought that the undesirables is the cause here.... [123Venom/plugin.video.venom#151 (comment)](https://github.com/123Venom/plugin.video.venom/issues/151#issuecomment-991200761)
> 
> @Tinuz97 as for your log errors. I don't think those are the cause of the issue either. A good many of those log errors are coming from the cfscrape/cloudflare module and unfortunately that's written by Venomous and I'd have to get in touch with him on the user agent assignment failure because it's not my code. You have some connection issues going on there also that I'm not sure if they're blocked for you or not.

If I turn off Undesirables in Fenomscrapers, everything is working again 🙂.

**Comment by 123Venom** [comment]
That link I posted has my hunch on what's happening.  Did you ever make any changes to the undesirables via the settings?  There are two methods to do so.  One is you can enable/disable items from the default list.  The option below that allows you to add your own default strings.  Have you ever used those?  I have not touched them myself so the code added in v2.0.1 is really not used in my case and may be why it's still working fine here in both Venom and Fen....again only a hunch since people effected by this disable the undesirables filter and it cures the issue.

**Comment by Tinuz97** [comment]
I use the Fenomscrapers 'stock'. Didn't toch Undesirables, only enabled all scrapers (long ago). 

The issue started since last update, so I have no idea.
In Dutch forums, many users experience the same 'issue' since last Fenomscrapers update, but I just leave the Undesirables disabled, because now it is working fine 🙂

**Comment by 123Venom** [comment]
Yes I understand this all happened last night on the v2.0.6 update, that's been repeated enough all over the place I get it.  I'm working on it...it's just damn hard to find when I can't reproduce it and the code handling that was not actually mine so this is going to take some time to resolve the matter.

Can you do me a favor.  In your **userdata** folder for **script.module.fenomscrapers** can you open the **settings.xml** and copy the full line that starts with **<setting id="undesirables.choice">**

**Comment by cgcgcgcgcg** [comment]
> 

<setting id="undesirables.choice">,casstudio.tv,pa.web.dl</setting>

**Comment by cgcgcgcgcg** [comment]
> Yes I understand this all happened last night on the v2.0.6 update, that's been repeated enough all over the place I get it. I'm working on it...it's just damn hard to find when I can't reproduce it and the code handling that was not actually mine so this is going to take some time to resolve the matter.
> 
> Can you do me a favor. In your **userdata** folder for **script.module.fenomscrapers** can you open the **settings.xml** and copy the full line that starts with **setting id=undesirables.choice**

<setting id="undesirables.choice">,casstudio.tv,pa.web.dl</setting>

**Comment by Tinuz97** [comment]
> 

<setting id="undesirables.choice">,casstudio.tv,pa.web.dl</setting>

**Comment by Tinuz97** [comment]
<setting id="undesirables.choice">,casstudio.tv,pa.web.dl</setting>

**Comment by 123Venom** [comment]
> udio.tv,pa.web.dl

Unfortunately there's the problem.  That leading `,` is going to break it.  Plus that is intended to be a full list of the undesirables
Here's mine and why it did not break for me

```
400p.octopus,720p.octopus,1080p.octopus,alexfilm,amedia,audiobook,baibako,bigsinema,bonus.disc,casstudio.tv,courage.bambey,.cbr,.cbz,coldfilm,dilnix,dutchreleaseteam,e.book.collection,empire.minutemen,eniahd,.exe,exkinoray,extras.only,gears.media,gearsmedia,gostfilm,hamsterstudio,hdrezka,hdtvrip,hurtom,idea.film,ideafilm,jaskier,kapatejl6,kb.1080p,kb.720p,kb.400p,kerob,kinokopilka,kravec,kuraj.bambey,lakefilm,lostfilm,megapeer,minutemen.empire,newstudio,omskbird,.ost.,paravozik,profix.media,rifftrax,sample,soundtrack,subtitle.only,sunshinestudio,teaser,trailer,tumbler.studio,tvshows,ultradox,viruseproject,vostfr,vo.stfr,web.dlrip,webdlrip,wish666,pa.web.dl,.p.web.dl,.d.web.dl

We'll sort that out and get that fix

**Comment by 123Venom** [comment]
@Tinuz97 can you test something for me.  In FS settings open the **Manage Default Undesirables** then go through and enable all of them.  Then re-enable the setting **Remove Undesirables** and see if that fixes it.  You can then review the strings it adds to that setting and tell me if there is stil a leading `,` cause that will break it.

There's no doubt an issue here to be fixed.  I'm just wanting a bit more insight in hand.

**Comment by Tinuz97** [comment]
> @Tinuz97 can you test something for me. In FS settings open the **Manage Default Undesirables** then go through and enable all of them. Then re-enable the setting **Remove Undesirables** and see if that fixes it. You can then review the strings it adds to that setting and tell me if there is stil a leading `,` cause that will break it.
> 
> There's no doubt an issue here to be fixed. I'm just wanting a bit more insight in hand.

That did the trick.

Now the line is:


    <setting id="undesirables.choice">400p.octopus,720p.octopus,1080p.octopus,alexfilm,amedia,audiobook,baibako,bigsinema,bonus.disc,casstudio.tv,courage.bambey,.cbr,.cbz,coldfilm,dilnix,dutchreleaseteam,e.book.collection,empire.minutemen,eniahd,.exe,exkinoray,extras.only,gears.media,gearsmedia,gostfilm,hamsterstudio,hdrezka,hdtvrip,hurtom,idea.film,ideafilm,jaskier,kapatejl6,kb.1080p,kb.720p,kb.400p,kerob,kinokopilka,kravec,kuraj.bambey,lakefilm,lostfilm,megapeer,minutemen.empire,newstudio,omskbird,.ost.,paravozik,profix.media,rifftrax,sample,soundtrack,subtitle.only,sunshinestudio,teaser,trailer,tumbler.studio,tvshows,ultradox,viruseproject,vostfr,vo.stfr,web.dlrip,webdlrip,wish666,pa.web.dl,.p.web.dl,.d.web.dl</setting>

**Comment by 123Venom** [comment]
yep...that now looks like mine.  So for some reason some ppl ended up with 
```,casstudio.tv,pa.web.dl```

While I on the other hand had the exact opposite.  I had all the old strings but those two new ones we not in there and I had no leading `,` so it didn't break for me.
